// src/components/WavingHand.tsx
import { createSignal, onCleanup, onMount } from "solid-js";

const WAVE_INTERVAL = 10000; // ms
const TRANSITION_TIME = 500; // ms

export default function WavingHand() {
  const [wave, setWave] = createSignal(false);

  function waveAndUnwave() {
    if (!wave()) {
      setWave(true);
      setTimeout(() => setWave(false), TRANSITION_TIME);
    }
  }

  onMount(() => {
    const timer = setInterval(waveAndUnwave, WAVE_INTERVAL);
    onCleanup(() => clearInterval(timer));
  });

  return (
    <div>
      <h1
        id="waving-hand"
        onMouseOver={() => setWave(true)}
        onFocus={waveAndUnwave}
        onMouseOut={() => setWave(false)}
        onBlur={() => setWave(false)}
      >
        <span
          class={`inline-block transition-transform ease-in ${wave() ? "rotate-[15deg]" : "rotate-0"}`}
          style={{ "transition-duration": `${TRANSITION_TIME}ms` }}
        >
          👋
        </span>
        😊
      </h1>
    </div>
  );
}

// src/lib/components/waving_hand.svelte
<script lang="ts">
	const waveInterval = 10000;
	let wave = false;

	function setWave() {
		wave = true;
	}

	function setNotWave() {
		wave = false;
	}

	function waveAndUnWave() {
		if (!wave) {
			setWave();
			setTimeout(() => {
				setNotWave();
			}, 500);
		}
	}

	// kick off the wave
	function wavePeriodically() {
		waveAndUnWave();
		setTimeout(wavePeriodically, waveInterval);
	}
	setTimeout(wavePeriodically, waveInterval);
</script>

<div>
	<h1
		class="text-8xl m-10"
		on:mouseover={setWave}
		on:focus={waveAndUnWave}
		on:mouseout={setNotWave}
		on:blur={setNotWave}
	>
		<span class={'hand ' + (wave ? 'waveIn' : 'waveOut')}> 👋 </span>
		😊
	</h1>
</div>

<style>
	.hand {
		display: inline-block;
	}
	.waveOut {
		transition: transform 0.5s ease-in;
		transform: rotate(0deg);
	}
	.waveIn {
		transition: transform 0.5s ease-in;
		transform: rotate(15deg);
	}
</style>
